# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wo < Formula
  desc "Workspace shell manager"
  homepage "https://github.com/antham/wo"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/antham/wo/releases/download/0.0.5/wo_0.0.5_darwin_amd64.tar.gz"
      sha256 "891ff5b0778ccca76ed4d963ecaf6b35e25e7b5cfccf9ae2e61774419b99cb88"

      def install
        bin.install "wo"
      end
    end
    on_arm do
      url "https://github.com/antham/wo/releases/download/0.0.5/wo_0.0.5_darwin_arm64.tar.gz"
      sha256 "44000e4b0a88828fa93bc226d14ba4a7b62c69a26279c9082d687fa019a36e61"

      def install
        bin.install "wo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/antham/wo/releases/download/0.0.5/wo_0.0.5_linux_amd64.tar.gz"
        sha256 "f2f4f534dd2700924f65d0ed3a27992b454bcaa74ec2e82a007ed9e3236b9da8"

        def install
          bin.install "wo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/antham/wo/releases/download/0.0.5/wo_0.0.5_linux_arm64.tar.gz"
        sha256 "c4340b07d02f078a689074dc73b18a27eb5e17132d7d82fac9d8fe58f4596193"

        def install
          bin.install "wo"
        end
      end
    end
  end
end
