# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wo < Formula
  desc "Workspace shell manager"
  homepage "https://github.com/antham/wo"
  version "0.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/antham/wo/releases/download/0.0.3/wo_0.0.3_darwin_amd64.tar.gz"
      sha256 "fcdae438dd8835987d653ba343ba69ba16575a60693911591a7ddbaaa5ad130e"

      def install
        bin.install "wo"
      end
    end
    on_arm do
      url "https://github.com/antham/wo/releases/download/0.0.3/wo_0.0.3_darwin_arm64.tar.gz"
      sha256 "8192ec3af6d3f475377eafc9131ae57dc5695911439b239531e7a58c421fe610"

      def install
        bin.install "wo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/antham/wo/releases/download/0.0.3/wo_0.0.3_linux_amd64.tar.gz"
        sha256 "6586126a007e1882e4b2293cf587cea0d3d8e90e45bdbf2c0bd9e9fc6ba50ffd"

        def install
          bin.install "wo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/antham/wo/releases/download/0.0.3/wo_0.0.3_linux_arm64.tar.gz"
        sha256 "e8a48f50508e76d42018eb0f66cdd094688d92c0145b97791589a8645220acef"

        def install
          bin.install "wo"
        end
      end
    end
  end
end
